### PR TITLE
A "ludicrous" small version

### PR DESCRIPTION
**Pull request by WebReflection**
Keeping all tests identical, I've managed to shrink the code even more.

https://www.youtube.com/watch?v=oApAdwuqtn8

### CODE REVIEW

**Comment by RReverser** [comment]
Can you post the size output?

**Comment by WebReflection** [comment]
Screenshot from 2019-05-24 13-24-19

**Comment by WebReflection** [comment]
I also didn't even think about benchmarks, but I've seen the reduce based version and I'd say I like that the most. It's even faster, but at this point there's no reason to push this forward.

I'll close 🎉

Screenshot from 2019-05-24 13-34-14

**Comment by RReverser** [comment]
Just to add 5c: your version can be trimmed down even further :)

```javascript
export default function dlv(obj, key, def, p, undef) {
	key = key.split ? key.split('.') : key;
	while ((p = key.shift()) !== undef) {
		obj = obj ? obj[p] : undef;
	}
	return obj === undef ? def : obj;
}
```

Size:

```
118 B: dlv.js.gz
86 B: dlv.js.br
117 B: dlv.es.js.gz
88 B: dlv.es.js.br
193 B: dlv.umd.js.gz
160 B: dlv.umd.js.br
```

And even more if we slightly change semantics and assume that no one uses `obj['']` as a property (which they, hopefully, don't):

```javascript
export default function dlv(obj, key, def, p, undef) {
	key = key.split ? key.split('.') : key;
	while (p = key.shift()) {
		obj = obj ? obj[p] : undef;
	}
	return obj === undef ? def : obj;
}
```

Size:

```
115 B: dlv.js.gz
82 B: dlv.js.br
114 B: dlv.es.js.gz
86 B: dlv.es.js.br
189 B: dlv.umd.js.gz
153 B: dlv.umd.js.br
```

**Comment by WebReflection** [comment]
> And even more if we slightly change semantics and assume that no one uses obj[''] as a property (which they, hopefully, don't):

yeah, that was my first attempt, but then it was failing tests so I opted for the current one.

**Comment by WebReflection** [comment]
I've updated the PR with the intermediate version for record sake, while mine PR was:

```js
export default function dlv(obj, key, def, p, undef) {
	key = key.split ? key.split('.') : key;
	while (key.length) {
		p = key.shift();
		obj = obj ? obj[p] : undef;
	}
	return obj === undef ? def : obj;
}
```

**edit** never mind, after closing it, it didn't care about my update

**Pull request closed without merging**
